sudo: required
before_install:

  - sudo apt-get -y update
  - sudo apt-get install -y language-pack-en-base
  - sudo LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php5-5.6
  - sudo apt-get -y update
  - sudo apt-get -y install php5 php5-mhash php5-mcrypt php5-curl php5-cli    
  - sudo php -r "readfile('https://getcomposer.org/installer');" | php
  - cd /home/travis/build/Averell7
  - sudo mkdir flarum
  - cd flarum
  - sudo php /home/travis/build/Averell7/Pdfbooklet2/composer.phar create-project flarum/flarum . --stability=beta
  - sudo php /home/travis/build/Averell7/Pdfbooklet2/composer.phar require vingle/flarum-configure-smtp hyn/flarum-guardian
  
install: 
  - ls


after_success: 
  - sudo python export_flarum.py
