sudo: required
before_install:
#  - sudo php -r "readfile('https://getcomposer.org/installer');" | php
  - sudo curl -sS https://getcomposer.org/installer | php 
install: 
  - pip install php

before_script:
  - flake8
  - mkdir -p shippable/{codecoverage,testresults}

script: 
  - tox -e py${TRAVIS_PYTHON_VERSION/\./}
  
after_install:
 - sudo ls
 
